from flask import Blueprint, jsonify
from models import Animal
from extensions import db

report_bp = Blueprint('reports', __name__)

# GET /reports/animals: Retrieve a report on the number and distribution of animals in the zoo
@report_bp.route('/reports/animals', methods=['GET'])
def animal_report():
    from sqlalchemy import func

    report = db.session.query(
        Animal.species,
        Animal.gender,
        func.count(Animal.id).label('count')
    ).group_by(Animal.species, Animal.gender).all()

    result = [{'species': species, 'gender': gender, 'count': count} for species, gender, count in report]
    return jsonify(result), 200

# GET /reports/visitors: Retrieve a report on the number and behavior of visitors in the zoo
@report_bp.route('/reports/visitors', methods=['GET'])
def visitor_report():
    report = [
        {'ticket_type': 'Adult', 'date': '2024-10-01', 'count': 200},
        {'ticket_type': 'Child', 'date': '2024-10-01', 'count': 50},
    ]
    return jsonify(report), 200

# GET /reports/revenue: Retrieve a report on the revenue generated by the zoo
@report_bp.route('/reports/revenue', methods=['GET'])
def revenue_report():
    report = [
        {'ticket_type': 'Adult', 'event_type': 'General Admission', 'date': '2024-10-01', 'revenue': 2000},
        {'ticket_type': 'Child', 'event_type': 'General Admission', 'date': '2024-10-01', 'revenue': 500},
    ]
    return jsonify(report), 200